- hosts: 172.31.36.60
  tasks:
    - name: cleaning files
      shell: rm -rf ~/test5

    - name: pull
      shell: git clone -b master https://github.com/Saumil343/test5.git

    - name: docker kill
      shell: docker stop phpapp4 || true && docker rm phpapp4 || true
    
    - name: docker build
      shell: docker build -t saumil343/demoapp5 ~/test5/
      
    - name: docker run 
      shell: docker run -it -d --name phpapp4 -p 80:80 saumil343/demoapp5
