---
- hosts: 172.31.36.60
  tasks:
    - name: saunil
      shell: rm -rf /var/www/html/geek/*

    - name: cleaning files
      shell: rm -rf ~/test5

    - name: pull
      shell: git clone https://github.com/Saumil343/test5.git

    - name: copy
      shell: cp -r ~/test5 /var/www/html/geek/
      
    - name: service1
      service:
        name: httpd
        state: restarted
   